openapi: 3.0.3

info:
  title: STD23017 - TD5
  version: 1.0.1

paths:
  /customers/{customerId}:
    put:
      description: Entirely update an existing customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"

      responses:
        "200":
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

    patch:
      description: Partially update an existing customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              properties:
                id:
                  type: string
                name:
                  type: string
                yearsOld:
                  type: integer

      responses:
        "200":
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

components:
  schemas:
    Customer:
      type: array
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
